### ISSUE TITLE
Does this work on Godot v4.1.2?

### ISSUE THREAD

**Issue by stik101** [jefvel/newgrounds-godot-4#1]
The asset library page says that it is up to date to 4.2x, but will it work on 4.1.2?

i haven't tested it out yet, since the game's not done yet, and that i want to avoid last minute panic on integrating it with the api.

Thx, cheers!

**Comment by jefvel** [comment]
Hmm, I'm not sure, haven't tested it myself. I think it should work though. It would be best to just try it out

**Comment by stik101** [comment]
it works! i checked rn. thx!
