### ISSUE TITLE
  Parse JSON failed. Error at line 0:  Invalid get index 'success' (on base: 'Nil').

### ISSUE THREAD

**Issue by stik101** [jefvel/newgrounds-godot-4#2]
So i tried importing my medals, but it showed something like this;

Newgrounds.io - Getting medals and scoreboards...

  Parse JSON failed. Error at line 0: 
  res://addons/newgrounds/scripts/newgrounds_request.gd:150 - Invalid get index 'success' (on base: 'Nil').
  Parse JSON failed. Error at line 0: 
  res://addons/newgrounds/scripts/newgrounds_request.gd:150 - Invalid get index 'success' (on base: 'Nil')

Can someone tell me why it shows like that?

**Comment by jefvel** [comment]
Hmm. Have you added your app ID and secret to the project settings?

If you have, could you add `print(body_string)` to line 147 in the script `addons/newgrounds/scripts/newgrounds_request.gd` and see what it says when you run the import?

**Comment by jefvel** [comment]
After we investigated it a bit on the newgrounds.io discord, it seems like this has to do with regional restrictions on the newgrounds API itself, which is not super straight forward to fix.
 
I updated the addon to print error messages when it fails, but can't solve the main issue sadly :(
