### ISSUE TITLE
Unable to write to file when medal has "?" in it

### ISSUE THREAD

**Issue by Pab10Suarez** [jefvel/newgrounds-godot-4#3]
![image](https://github.com/jefvel/newgrounds-godot-4/assets/29072142/8429fe1d-e415-45c7-85c5-538b00019760)
i was importing medals and leaderboard but the ? symbol made this message appear, i got ride of the symbol it and it worked without problem

**Comment by jefvel** [comment]
This should be fixed now if you update the addon
